[[redirects]]
  from = "/*"
  to = "index.html"
  status=200

[[redirects]]
  from = "/RBCBlackHistoryMonth"
  to = "../src/RBCBlackHistoryMonth/jsx"
  status=200

[[redirects]]
  from = "/BirthdayNFT"
  to = "../src/BirthdayNFT/jsx"
  status=200

[[redirects]]
  from = "/BirthdayNFT/KLPNFT"
  to = "../src/BirthdayNFT/KLPNFT/jsx"
  status=200
  
[[redirects]]
  from = "/BirthdayNFT/VICNFT"
  to = "../src/BirthdayNFT/VICNFT/jsx"
  status=200